autoload/handlers.vim
autoload/lspoptions.vim
doc/lsp.txt
plugin/lsp.vim

This add an option `g:LSP_Hover_Reply_In_Preview` which permit to see hover result in a preview window.

Add : possibility to get hover result in preview window

---

autoload/handlers.vim

Avoid ` E715: Dictionary required` if lsp server does not provide the kind of reply.
This try to solve the problem encountred by @Shane-XB-Qian  in https://github.com/yegappan/lsp/issues/22#issuecomment-970182311

Fix : Better ft detection for preview widow on hover reply

---

autoload/diag.vim
autoload/lsp.vim
autoload/lspoptions.vim
autoload/outline.vim
doc/lsp.txt
plugin/lsp.vim

- Option to show diagnostics on status line
- Option to close on select on reference window
- Option to not suppress the diag hover appearing on mouse hover
- Make outline configurable
- Option to suppress adding a new line on completion selection

Optional vim-lsc like behaviours

---

autoload/lsp/handlers.vim

shane/mdf: to avoid if location (result) of defDecl was null

---

autoload/lsp/lspserver.vim

shane/mdf: request.id of response to lsp server perhaps was not a number

---

autoload/lsp/handlers.vim
autoload/lsp/lsp.vim
autoload/lsp/lspserver.vim

This PR add `completionItem/resolve` functionality to retrieve the documentation in lazy way.
The detail text has been added at the beginning of the documentation popup (keeping it as `d.menu` take too much space at least with java/jtd lsp) and `completepopup` property has been changed to make the documentation popup to look better: to check if this changes are ok also for the others lsp servers.
The old code/property are still used when `completionItem/resolve` functionality is not available with the lsp server: to consider whether the above changes also make sense in this case.

Lazy documentation for selected completion item

---

autoload/lsp/lsp.vim
plugin/lsp.vim

add LspServerStatus(ft) func to detect ft lsp server was running or not (or not found)

Pr ft server status

---

doc/lsp.txt

fix: refine code action doc

---

.github/workflows/unitests.yml
test/unit_tests.vim

Pr ci clangd 14

---

.gitignore
test/run_tests.sh

refine test case script which made it more robust or correct, or fail sometime.

Pr correct test script

---

autoload/lsp/lspserver.vim

maybe not ready or somehow there is no 'result'

fix: somehow 'reply' may not have 'result' (or not yet)

---

autoload/lsp/completion.vim

otherwise there flaky broken/err sometimes....

fix: compl item maybe is 'string'!

---

autoload/lsp/options.vim
doc/lsp.txt
plugin/lsp.vim

let user be easier to access lsp option, specially in func.

adding 'OptionsGet' func

---

autoload/lsp/completion.vim

the reply.result of complete resolve perhaps is null.

Pr completion resolve item null

---

autoload/lsp/lsp.vim
autoload/lsp/outline.vim
test/unit_tests.vim

Signed-off-by: shane.xb.qian <shane.qian@foxmail.com>

fix: make lsp hl not be overrode by cursorline

---

autoload/lsp/codeaction.vim

not sure if was an accurate fix, but command of cmd maybe not existed anyway.

fix: codeaction command of cmd maybe not existed

---

autoload/lsp/lsp.vim
autoload/lsp/options.vim
doc/lsp.txt
plugin/lsp.vim

`lineHL` was unfortunate for me by default, so I added `diagLineHL` to lspOptions.

lspOptions: diagLineHL

---

autoload/lsp/callhierarchy.vim
autoload/lsp/lsp.vim
plugin/lsp.vim

145 fix show diag on status line

---

README.md

Fix the unit test badge src

---

autoload/lsp/completion.vim

This is a very naive way to add support for `CompletionItem.textEdit`, it addresses the problem mentioned in #130  but doesn't respect the specifications, as the range isn't actually respected but simply used to slice the beginning of the returned `textEdit.insertText`. 
Closes #130

Add naive support for textEdit

---

autoload/lsp/completion.vim

pr #160 was missed closed, so reopen a new one for it.

fix: omnifunc broken

---

README.md
autoload/lsp/diag.vim
doc/lsp.txt
plugin/lsp.vim
test/clangd_tests.vim
test/tsserver_tests.vim

// jump to the diag msg in this/current line
// start from current column of current line

feature: adding 'LspDiagThis'

---

autoload/lsp/diag.vim
autoload/lsp/lsp.vim
autoload/lsp/options.vim
doc/lsp.txt

Hi, I like your project and use it in my main .vimrc 
I suggest adding optional diagnostic messages inline display

add diagnostic messages display with virtual text and pointer

---

autoload/lsp/lspserver.vim
test/run_tests.sh

Add error messages etc

---

autoload/lsp/diag.vim

Render visual selection over inline diag

---

autoload/lsp/completion.vim

before this update 
if we use completion not in the start of line or edit code completion function get all list of snippets for this buffer 
now we filter snippets with matchfuzzy()

fix: add filter to ultisnip list

---

autoload/lsp/completion.vim

this change prevent lazy load documentation request to LSP server for items that already  consist documentation 
fix issue https://github.com/yegappan/lsp/issues/215

add fix to not LSP documentation with tsserver lsp

---

autoload/lsp/completion.vim
autoload/lsp/options.vim
doc/lsp.txt

I've tested it, and worked properly, i wanted this for too long time, so, i've implemented on my own

feat: Add custom completion kind

---

autoload/lsp/completion.vim
autoload/lsp/options.vim
doc/lsp.txt

feat: make additionalTextEdits be possible to disable

---

autoload/lsp/lsp.vim

It's only possible to initialize completion when all server capabilities are known, as this is the time it's known which server will end up being used for completion.
Before this PR, the completion would be initialized once / server

Initialize completion when all server capabilities are known

---

autoload/lsp/completion.vim

this  change fix ultisnip description when in description we can see info for not one snippet

small fix for ultisnip description

---

autoload/lsp/buffer.vim
autoload/lsp/diag.vim
doc/lsp.txt

Make it possible to disable language server features
Make it possible to disable diagnostics from a specific server.

Disable diags for specific server

---

autoload/lsp/handlers.vim
autoload/lsp/inlayhints.vim
autoload/lsp/lsp.vim
autoload/lsp/util.vim

Fix tidy echom

---

autoload/lsp/buffer.vim
autoload/lsp/codeaction.vim
autoload/lsp/completion.vim
autoload/lsp/diag.vim
autoload/lsp/handlers.vim
autoload/lsp/lsp.vim
autoload/lsp/lspserver.vim
autoload/lsp/textedit.vim
autoload/lsp/util.vim
test/clangd_tests.vim

// uniform the err/wrn msg fmt.

Feat: util msg fmt

---

autoload/lsp/diag.vim

Just in case you take care of avoiding code duplication within this code base
this PR cleans up some obvious code duplicates within the file ```autoload/lsp/diag.vim```
Feel free to advise a better name for the new function ```RemoveDiagVisualsForBuffer```

Cleanup of code duplications for diagnostics.

---

autoload/lsp/lspserver.vim

Add headline to language server message

---

autoload/lsp/buffer.vim

Remove return after throw

---

README.md
doc/lsp.txt

Updated documentation with options example and reordering

---

autoload/lsp/completion.vim
autoload/lsp/lspserver.vim

See the following for details: https://asciinema.org/a/4befgFC84Vt2k6Hqdr4Wd8EaK

Add support for lazy documentation and omni completion

---

autoload/lsp/diag.vim

Always switch to correct loclist after running `:LspShowDiags`

---

test/gopls_tests.vim

This will make it easier to merge #302

Save bufnr() in a variable instead of inlining it

---

autoload/lsp/diag.vim
autoload/lsp/lsp.vim

Conditionally override cursor for props when "&cursorline" is set
Closes #322

Conditionally override cursor for props when "&cursorline" is set

---

autoload/lsp/util.vim

Speed up cygwin path transformation.

---

.gitignore

// since you modified the tmp testing fs name.

fix: correct test fs gitignore

---

autoload/lsp/markdown.vim

Handle tabs and soft/hard line breaks

Markdown parser enhancement

---

autoload/lsp/inlayhints.vim

fix(inlayhint): fix format when label is a list in Rust Analyzer

---

README.md

Newbies only copy and paste settings
T. T

Copy to my vimrc Error!!

---

autoload/lsp/handlers.vim

Fixes https://github.com/yegappan/lsp/issues/410 and https://github.com/yegappan/lsp/issues/400

Changed default value of missing workspaceConfig from [{}] to [null]

---

autoload/lsp/handlers.vim

fix: check cfg get len

---

autoload/lsp/codeaction.vim

it maybe messed digit with str

none: refine code action regex a bit

---

README.md
autoload/lsp/completion.vim
autoload/lsp/options.vim
doc/lsp.txt

Fixes https://github.com/yegappan/lsp/issues/433
Note, this solution seems to work for volar and php lsp, I'm unsure of how it will behave in other servers.
Feedback i welcome on what keys should be used when comparing completion items.

Added option for removing duplicate completion items

---

autoload/lsp/completion.vim

extract to check compl sel item

none: compl item sel

---

autoload/lsp/handlers.vim

tmp impl 'showMessageRequest' like 'showMessage'

feat: tmp impl 'showMessageRequest'

---

README.md
doc/lsp.txt

Add tags generation instruction to README and lsp.txt

---

README.md
doc/configs.md

Since the Wiki is locked, add a document documenting LS setups similar to https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md to allow curated contributions (as in https://github.com/yegappan/lsp/issues/601);
also point out loc.cit. as fallback.

move Wiki to doc/ for possible PRs on setting up LSs

---

plugin/lsp.vim

export needs import of the source file but g: not

LspFormatFunc: make truly global

---

autoload/lsp/codeaction.vim
autoload/lsp/options.vim
doc/lsp.txt

This PR adds the popup configuration of border
and highlight to the CodeAction popup.

PR#627 lacks popup configuration support for CodeAction

---

doc/lsp.txt

Simple typo I needed to fix to make it work.

Add missing "g:" to call to LspAddServer

---

doc/configs.md

Added a few missing commas and hashes in dictionaries passed to LspAddServer.

Update dictionaries to fix syntax errors in LSP configs
