yegappan/lsp

README.md
autoload/lsp.vim
doc/lsp.txt

// when `let g:LSP_24x7_Complete = v:false`,
some compl from lsp maybe not a good way / user like,
or whatever user may like his/her preferred omnifunc which not override by this plugin.
```vim
let lspServers = [
\     {
\	'filetype': ['javascript', 'typescript'],
\	'omnicompl': v:true,
\	'path': '/usr/local/bin/typescript-language-server',
\	'args': ['--stdio']
\     },
\     {
\	'filetype': 'python',
\	'omnicompl': v:false,
\	'path': '/usr/local/bin/pyls',
\	'args': ['--check-parent-process', '-v']
\     }
\   ]
```
To allow user can disable omnicompl for specific ft.
- adding a 'omnicompl' option in configuration.
- default (or if not set) 'omnicompl' is true.

To allow disable omnicompl for specific ft.

---

autoload/handlers.vim
autoload/lsp.vim
doc/lsp.txt
plugin/lsp.vim

- if g:LSP_24x7_Complete is false
// auto show signature looks a bit delay, not work smoothly always..
// specially those 'inoremap' would override user's key map, perhaps not a good idea..
// so should be better to enable auto show signature Like auto completion Only IF g:LSP_24x7_Complete is true (default though).

disable auto showSignature

---

autoload/handlers.vim
doc/lsp.txt
plugin/lsp.vim

This add an `g:LSP_Echo_Signature` option which permit to see signature of a symbol echoed in cmdline rather than displayed in a popup window.

Add : Possibility to echo signature in cmdline

---

autoload/lsp.vim

Can be used to display error count in status bar or with vim-airline.

Add add function to get error count for the current buffer

---

autoload/util.vim

When get handler#processDocSymbol, textDocument.uri does not begin with
'file://', so util#LspUriToFile truncate the file name.

Fix util#LspUriToFile with handler#processDocSymbolReply

---

autoload/lsp/handlers.vim

make annoyed telemetry/event ntf only ntf once
refine: https://github.com/yegappan/lsp/pull/53#issuecomment-1065509804
// case from 'yaml language server'

shane/mdf: adding ntfOnce func and make unsupported telemetry/event ntf only ntf once

---

autoload/lsp/lspserver.vim

The tabSize field in the LSP spec is poorly named, as it's not used for tabs but rather the indent size when formatting.  This corresponds to `shiftwidth()` in Vim.
This is also the approach taken by [coc.nvim](https://github.com/neoclide/coc.nvim/blob/287c743c9f227fdf0e1db452bbb8ae3c5caffc36/autoload/coc/util.vim#L868-L871) and [Neovim](https://github.com/neovim/neovim/blob/1184097261260e53519db54548acf2c1e5ab7e68/runtime/lua/vim/lsp/util.lua#L1905-L1906).
If there's some reason not to do this, the code should instead be updated to use `shiftwidth()` so that `shiftwidth=0` is handled correctly, and possibly to respect `'smarttab'`.

Use shiftwidth() as tabSize

---

autoload/lsp/lsp.vim
doc/lsp.txt

This provides a hook for users to configure buffers that use LSP. For
example,
autocmd User LSPAttached {
nnoremap <buffer> <C-]> <Cmd>LspGotoDefinition<CR>
}

Fire event when LSP client is attached to a buffer

---

autoload/lsp/lsp.vim
autoload/lsp/lspserver.vim
doc/lsp.txt

* Removes isSync as parameter from StartServer(..), InitServer(..)
* Adds isSync parameter to NewLspServer(...)
* Adds `sync` to lspserver-properties (Defaults to `sync: false` in LspServer dictionary).

lspserver: sync property

---

README.md
autoload/lsp/lsp.vim
autoload/lsp/lspserver.vim
doc/lsp.txt

This is to add support for LSP server initializationOptions. For me it was important to allow transmission of the licenseKey to the intelephense PHP language server, however it is a standard field and other servers configurations may require these too.
Some of configurations are (or may be) expected to be determined by the editor ('LSP client') however this should require individual per-server 'wrappers' or something similar.
* Add 'initializationOptions' as LSP server configuration option.
* Check if 'initializationOptions' are not empty and if so transmit these to the LSP server
* Updated README.md
* Updated plugin documentation

Provide LSP server initializationOptions support

---

autoload/lsp/diag.vim
autoload/lsp/options.vim
doc/lsp.txt

Added a option to show diagnostics in a floating popup
The option name is `showDiagInPopup` and it's default is `false`

Add option to show diagnostics in a popup

---

autoload/lsp/handlers.vim

Fix some new line issues in the completion popup and in the completion detail popup
> Before:
> After:
> Before:
> After:

Fix new lines in completion popup and in the completion detail popup

---

autoload/lsp/symbol.vim

closes #9 
`fname->bufwinid()` perhaps randomly pick up one, but cur window perhaps was the same buf
// so firstly pick up cur buf if was same buf, then same buf in cur tab if there was one,
// or if none of them, then randomly pick one, or not found.

fix: not jump if cur one is same buf also

---

autoload/lsp/codeaction.vim
autoload/lsp/options.vim
doc/lsp.txt

Added a option called `usePopupInCodeAction`
If the option is enabled, the command ":LspCodeAction" will use it to show the code action in a popup window

Create custom popup for code action and added a option to enable/disable it

---

autoload/lsp/lspserver.vim

When enabling TraceLog to debug a lsp server, it is usefull to have also the messages sent to it.

Add sent messages to TraceLog

---

autoload/lsp/codeaction.vim

Both the `CodeAction` and `Command` interfaces contain the `command` member
but these should be handled differently for them. Corrected the
`HandleCodeAction` method to correctly handle these.
Tested with _intelephense_ PHP language server and _clangd_.

Correct HandleCodeAction behavior for CodeAction

---

README.md
autoload/lsp/lsp.vim
autoload/lsp/lspserver.vim
doc/lsp.txt

* Corrected `initializationOptions` field type. According to specification this should be of type `LSPAny` - so `any` is used
* Corrected `PHP` language server configuration section
* Added description of the `initializationOptions` field
* Added hint on `LspFormat` command since it is not obvious which indentation options are used and how indentation may be controlled

initializationOptions and doc corrections

---

autoload/lsp/lsp.vim

Add `CompleteDone` autocommand handler to verify if activated completion require additional text edits ('server-initiated edits') and to perform these.
The additional text edits are used for example when an import is required for the completed entity.

Add CompleteDone handler to execute text edits

---

autoload/lsp/codeaction.vim

to make the code action operation a bit convenience:
1, make code action popup can be selected by item num
2, 'h/l' key can be used to close code action popup as well

feat: make code action popup can be selected by item num

---

autoload/lsp/lspserver.vim

`textDocumentSync` maybe just a 'number' not a 'dict', which seems meant 'change' or 'saveKind' as per lsp specification.
// But actually i am not very confident on what i changed, though it works for now. 
// pls review and/or refine a bit later if needed.

fix: correct the 'didSave' check

---

autoload/lsp/hover.vim
autoload/lsp/lsp.vim
autoload/lsp/lspserver.vim
autoload/lsp/markdown.vim
ftplugin/lspgfm.vim
syntax/lspgfm.vim

The second commit uses the markdown parse for hover popup as well and add a proposal change to management of MarkedString text as  per [Specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#markedString); not sure if it is correct for all language servers, tested only with jdt java server.
I think it would by nice to put completion details part into a fenced block, but I don't know where to retrieve to correct language within `CompletionResolveReply` method, not sure also if it will look good with all language servers.

Lsp markdown parser for popup documentation

---

autoload/lsp/completion.vim

lsp info document maybe not a dict type

fix: should check type of complete_item.doc

---

autoload/lsp/handlers.vim
autoload/lsp/lspserver.vim

fix issue found at bash lsp server https://github.com/bash-lsp/bash-language-server/pull/535
but `workspace/workspaceFolders`  method was not really worked, 
and `sendResponse()` code logic of judge `errer` and `result` type was wrong.
this pr is trying to address and fix that.
Signed-off-by: shane.xb.qian <shane.qian@foxmail.com>

feat: make workspace/workspaceFolders really work and correct sendResponse func

---

plugin/lsp.vim

Useful to detect if the plugin was loaded before doing things in, for example, `.vim/after/plugin/lsp.vim` by doing:
```
if !get(g:, 'loaded_lsp') | finish | endif
```

Add g:loaded_lsp variable for easy detection

---

plugin/lsp.vim

This kind of bailout does not work with vim9 without `vim9script noclear`. See `:h vim9-reload`.
Fixes: #122

Remove early bailout check

---

autoload/lsp/diag.vim

The function `items({dict})` returns a list in arbitrary order, and it would be nice that the errors are sorted by how the occur in the source file.

Sort the diagnostics by line number when populating the location-list

---

autoload/lsp/handlers.vim

Ignore the "$/typescriptVersion" custom notification send by this language server:
https://github.com/typescript-language-server/typescript-language-server

Ignore TypeScript language server custom notification

---

autoload/lsp/symbol.vim

While using `lsp#lsp#TagFunc`, `CTRL-]` jumps to proper line, but not the proper column. This PR makes it jump to proper column using the LSP character position.

fix: Use character position in TagFunc

---

README.md
autoload/lsp/handlers.vim
autoload/lsp/lsp.vim
autoload/lsp/lspserver.vim
doc/lsp.txt
test/unit_tests.vim

We need to discuss all the details, currently this MR adds a new property to the "AddServer" dictionary, which when provided will extend and override existing notification handlers.
1. Does it make sense to override the existing notification handlers, or should it only be possible to provide new?
2. Does it make sense to "leak" the internal API `(lspserver, reply)`? Or should only `reply.params` be send?

Add support for "customNotificationHandlers"

---

autoload/lsp/lspserver.vim
autoload/lsp/symbol.vim
autoload/lsp/util.vim

This change should be backward compatible, but allow us to use all the properties from "LocationLink" in other commits, as long the language server replies with "LocationLink".
Closes #141

Add support for "capabilities.*.linkSupport"

---

autoload/lsp/codeaction.vim
autoload/lsp/options.vim
doc/lsp.txt

As of 3.16.0 of the [specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeAction) a code action can contain a `disabled` object, sniff on this object and remove disabled code actions if the `hideDisabledCodeActions` option is set.

Hide disabled code actions

---

autoload/lsp/completion.vim

Currently when using:
call LspOptionsSet(#{ autoComplete: v:false })
Omni completion is set, but the partially typed word isn't respected when completing, consider the following:
$ cat a.c
int foo = 1;
int frog = 1;
int bar = 1;
int main() {
int a = f|
}
Cursor is `|` typing `<C-x><C-o>` the list will contain all three integers: `foo`, `frog`, and `bar`. I would expect only `foo` and `frog`.
Currently it's really hard to write a test for this, as it's not possible to change the "autoComplete" option after the buffer have been initialized, as autocmds and vim options are being set in `BufferInit`.
I think one solution to this problem would be to refactor the current code, to internally react to autocmds when the options have been changed. Alternative the default for the tests should to …

Support partially typing the omni completed keyword

---

autoload/lsp/lspserver.vim

The typescript-language-server will provide better code actions when knowing which column you stand on.
For instance the "add missing import" action works more reliable when the server knows the current column.

Send charcol when requesting code action

---

autoload/lsp/lspserver.vim
test/unit_tests.vim

This works somewhat like "CTRL-]" and "CTRL-R_CTRL-W".

Scan for the closest identifier under the cursor when resolving cursor location

---

autoload/lsp/util.vim

I think editing another buffer will automatically add an entry to the jumplist, meaning that we don't need to set the `'` mark.
See the two following videos:
Before: https://asciinema.org/a/FwgclnvOatJYiG9BUZpyoGc7q (Notice how the first press of `^O` jumps to the first line in the new file.
After: https://asciinema.org/a/llmaYSnSOP420hkhQbZ86XNnj

Don't add two entries to the jump list when jumping to a symbol in another file

---

autoload/lsp/completion.vim

The specifications states:
> for speed clients should be able to filter an already received
> completion list if the user continues typing. Servers can opt out of
> this using a CompletionList and mark it as isIncomplete
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion
Please see attached video: https://asciinema.org/a/4pGB1vszSpaXQp0SDKfGIhozI
Closes #160 , #164

Respect "isIncomplete" when filtering completion items

---

autoload/lsp/diag.vim
autoload/lsp/lsp.vim
autoload/lsp/lspserver.vim
test/run_tests.sh
test/runner.vim
test/tsserver_tests.vim

Sometimes multiple errors can occur on the same line, for instance, the following TypeScript code includes two errors:
```typescript
export obj = {
foo: 1,
bar: 2,
baz: 3
}
```
```
a.ts|1 col 1 error| Declaration or statement expected.          
a.ts|1 col 8 error| Cannot find name 'obj'.
```
But only the last one is shown.
This PR adds support for having multiple diagnostics on the same line.

Add support for multiple diagnostics on the same line

---

autoload/lsp/lspserver.vim
autoload/lsp/symbol.vim
doc/lsp.txt
test/tsserver_tests.vim

This tries to address the main problem in #171
Bear with me, this is a bit larger PR:
The idea is to re-brand all the ShowReferences functions as generic ShowLocations functions.
By doing that the same core logic can be used for both showing references as well as showing multiple Definitions, TypeDefinitions, Inplementations, etc.
All the re-branded functions also gets support for [`LocationLink`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#locationLink), as these can be  in the reply data from the `textDocument/definition` methods.
Lastly a few tests have been added to the tsserver test file, I think these tests in theory could have been added to the `clangd` test file instead, as there isn't anything `tsserver` specific stuff being tested.

Hydrate loclist when multiple locations is replied from textDocument/definition, et al

---

autoload/lsp/completion.vim
autoload/lsp/options.vim
doc/lsp.txt

This only works for language servers which always sends the whole set of completion items to the client, like `tsserver`.
Which means this option wouldn't work for `clangd`.
This also makes it possible to opt-out of the ignore cased completion, which have been implemented in #157 and #167 
See a video of how it works here:
https://asciinema.org/a/ko4hFgnzoMUqSVQlvxI1u8OlS

Add "completionMatcher" which can be set to "icase", "case" or "fuzzy"

---

autoload/lsp/diag.vim

Wrap popup text, to render it on multiple lines if needed:
Before: https://asciinema.org/a/FeoppIeHUkHi1UCL0iArHQD06
After: https://asciinema.org/a/5PAIjdvqhyIgQAneE7uUfxm7l
I'm not sure how write a proper test for this.

Wrap popup text

---

autoload/lsp/diag.vim

Diagnostics arrive asynchronous and the document might have changed before they reach the client.
This could cause the line number or column to be invalid when the diagnostics arrive.
Ignoring these errors isn't a big deal as new diagnostics will be send by the server shortly. And when there isn't any document changes, the client will be updated ASAP.

Ignore invalid lnum and column for prop_add

---

autoload/lsp/lspserver.vim
test/clangd_tests.vim

I think this configures `clangd` to talk utf-32, and also informs other servers that we would like to do the same.
I havn't been able to find any server that can be configured with [`general.positionEncoding`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#clientCapabilities) yet, but `clangd` have their own way to be configured which AFAIK works in `clangd14`.

Inform language servers that we really only supports utf-32

---

doc/lsp.txt

Add more tags in the doc file, as to allow to jump to help like: `lsp-opt-highlightDiagInline`, `lsp-cfg-initializationOptions`, and `LspDiagLine`.

Add more help tags

---

autoload/lsp/diag.vim
autoload/lsp/lsp.vim
doc/lsp.txt
plugin/lsp.vim
test/clangd_tests.vim

Make it possible to show diagnostics directly under the cursor, and not for the current line.
See the difference in this video:
https://asciinema.org/a/TVLSmVSoOjGxUzI5kRPTaMNp6

Add `:LspDiagCurrent!` to _only_ show diags if they are under the cursor

---

autoload/lsp/hover.vim
test/clangd_tests.vim

This related to the introduction of ":LspDiagCurrent!", Introduced in "be2221b~..4c93f5d", as the hover popup will be below the automatically shown diagnostic popup.
See video:
https://asciinema.org/a/EJlFPVOlp4oU8hqJqOWYntHqg

Hide diagnostic popup when ":LspHover" is used

---

autoload/lsp/hover.vim
test/clangd_tests.vim

Instead of showing an empty popup an error is shown when there is no hover:
I'm aware that some language servers already replies in a way that would result in no poup, but not the typescript-language-server.
This PR attempts to normalize the behavior across all language servers, by moving the hoverText calculation to its own function and draw the error if that function didn't return any hoverText.
Before | After
-------|-------
See video for example:
https://asciinema.org/a/S7urffOWgXtq8bwMXuJOPwz2W

Show error message instead of an empty popup when there are not content for ":LspHover"

---

autoload/lsp/completion.vim

There are no reason to add completion related autocmds, omnifunc etc, for servers that doesn't support it.
This was inspired by #219

Don't setup completion for servers that doesn't support it

---

autoload/lsp/lspserver.vim

// should respect the value of rootSearch after that feature.

fix: init workspace list was wrong if set rootSearch

---

autoload/lsp/lspserver.vim
doc/lsp.txt

- Use the CWD as the "rootUri" and initial "workspaceFolder"
- Use the parent directory for files not a descendent of the cwd
I think this makes more sense as a default, and it's also almost backward compatible for before ca7f26773bf4348d956e16d3d9dba82ca87c180c
It's hard to add a test as we reuse the LSP for every test.

Use cwd as rootUri and initial workspaceFolder for files within cwd

---

autoload/lsp/diag.vim

This PR adds range-end attributes of diagnostics to the location list, i.e. range.end to the corresponding end_col & end_lnum. Those are currently missing even though they are provided by the language server.

Add range-end attributes to diagnostic  location list.

---

autoload/lsp/lsp.vim
doc/lsp.txt

⚠️ This PR doesn't add support for running multiple LSP servers for a buffer, but rather adds support for registering multiple LSP servers for a given filetype.
The server with the longest workspace root will be chosen as the most relevant server for a given buffer.
Closes #221

Make it possible to have multiple servers registred for a given filetype

---

autoload/lsp/lsp.vim
autoload/lsp/lspserver.vim
plugin/lsp.vim

Since it's now possible to add "rootSearch" which changes the rootUri that is being send to the server I think it makes sense to be able to easily get to this information. I imagine it will be useful when people are reporting issues.
It might make sense to request people, that are doing bug reports, to include the information from:
:LspShowServer status
:LspShowServer initializeRequest
:LspShowServer capabilities
I understand that we already got `:LspShowServer messages` but that requires that logging is enabled, which requires the user to change the configuration and restart vim.

Add ":LspShowServer initializeRequest"

---

test/not_lspserver_related_tests.vim
test/run_tests.sh

The test will raise an exception like:
Error: Test Test_Helptags() failed with exception Vim(helptags):E154: Duplicate tag "lsp-opt-completionKinds" in file ../doc/lsp.txt at command line..script ~/.vim/pack/plugins/opt/lsp/test/runner.vim[50]..function <SNR>1_LspRunTests[20]..Test_Helptags, line 1
This test was created based on this comment https://github.com/yegappan/lsp/pull/234#issuecomment-1503656397

Add test to ensure that helptags can be generated without problems

---

autoload/lsp/textedit.vim

Some language servers like "efm-langserver" configured with "prettier" will provide multiple textedits for the same line and column, these are actually sorted "correctly" but since we apply the changes in reverse we need to also take the original sorting into account.
The range provided is something like:
{ start: { line: 10, character: 0 }, end: { line: 10, character: 0 } }
and this is the LSP servers way to provide an insert.

Take the original sorting into account when sorting textedits

---

README.md
autoload/lsp/buffer.vim
autoload/lsp/completion.vim
autoload/lsp/lsp.vim
autoload/lsp/lspserver.vim
doc/lsp.txt

These flags let the user choose which language servers should be used for which methods.
There are still a few places where there havn't been added "feature" flags, for instance:
'textDocument/switchSourceHeader'
'textDocument/signatureHelp'
'callHierarchy/incomingCalls'
'callHierarchy/outgoingCalls'
... and possible others as well
in these cases the first defined language server will be used.
The commits comes from https://github.com/yegappan/lsp/pull/231

multiple server part 9: Add support for the "features" configuration flags

---

autoload/lsp/lsp.vim

This makes it possible to configure a server to run within a given repository, by having a matched 'rootSearch', while having another one run for everything else.

Make servers with a non matching 'rootSearch' score below servers without 'rootSearch'

---

autoload/lsp/lsp.vim
autoload/lsp/lspserver.vim

This is to not fail if the user provides two servers with the same name.
Closes #271

Add an autocmd for the LSP servers internal ID

---

autoload/lsp/lsp.vim

The error message is something like: `Error: Language server for "xx" file type is not found`

Raise an error if no hover server is found

---

autoload/lsp/lspserver.vim
autoload/lsp/symbol.vim

Change to use a lambda instead of a funcref for the reply callback for dyc symbols, this allows us to move the `fname` to the end of the `symbol#DocSymbolReply` function.

Move `fname` to the end of the arguments in `symbol#DocSymbolReply`

---

autoload/lsp/lspserver.vim

This is the same problem that was fixed in #193 (3661dc0) as the highlight also arrive asynchronous.

Prevent raising errors when highlight arrive for deleted lines

---

autoload/lsp/completion.vim

With this, complete items should be sorted in the same way as Visual Studio Code (more or less). Unless the fuzzy matcher is enabled, <del>which then uses `matchfuzzy()` for sorting</del>.
Fixes #281

Sort complete items based on `sortText`

---

autoload/lsp/lspserver.vim

Some servers expects the object to be there. One being https://github.com/vuejs/language-tools
Closes #287

Always send "initializationOptions"

---

autoload/lsp/diag.vim

There is no reason not supporting enabling these options about initialization instead.
Closes #288

Remove option checks around prop_ declarations

---

autoload/lsp/util.vim

Language servers are compiled to use the standard Windows paths (although only tested with `rust-analyzer`). But `vim` under `Cygwin` uses POSIX paths. Therefore the paths have to be converted somewhere and `LspFileToUri` seems like the ideal place for it.
The added code detects if the script is being run from `Cygwin` and if so, it convert paths of the form "/cygdrive/c/foo/bar" to "c:/foo/bar" and paths of the form "/home/pete/foo" to "C:/cygwin64/home/pete/foo".
Feel free to suggest changes as this is my first non-one-liner vim script.

Adapt LspFileTorUri for Cygwin

---

autoload/lsp/util.vim

As suggested by @Shane-XB-Qian [here](https://github.com/yegappan/lsp/pull/297/files#r1188445597), the `cygwin` path conversion code can be simplified by using `cygpath`.

Simplify cygwin path conversions

---

README.md
doc/lsp.txt

The examples in the README were for the old vim, so I took the freedom to update them to vim9.
The same happened to the docs where I also found that there were a missing summary and I took the freedom to add a pinch of ascii art. 
I hope it won't bother! :)

Examples to vim9, added index and some ascii artwork in docs

---

autoload/lsp/handlers.vim
autoload/lsp/lspserver.vim

Eclipse java language server sends the 'workspace/executeClientCommand' request (to reload bundles) which is not in the LSP specification. Ignore this request and suppress the error message.
Fixed typos in lspserver.vim
M  autoload/lsp/handlers.vim
M  autoload/lsp/lspserver.vim

Ignore non-standard request from eclipse java LS

---

autoload/lsp/lsp.vim

Make it possible to define custom highlights for ref created via `:LspHighlight`.
Also prevent these highlights from overriding visual selection, hlsearch etc.

Custom ref highlight

---

autoload/lsp/diag.vim

With the following code:
```
#include <ctype.h>
#include <stdio.h>
void aFunc(void)
{
printf("%s", z, tolower("aaa"));
printf("%s", tolower("aaa"), z);
}
```
Line 5 and 6 will both be highlighted as errors, instead of today where line 5 will be highlighted as a warning, because `tolower("aaa")` overrides the error rendered by `z`.
The props used to highlight inline diagnostics are also being prioritized.

Add priority to props

---

autoload/lsp/diag.vim
autoload/lsp/options.vim
doc/lsp.txt
test/clangd_tests.vim

This option serves a similar purpose to `keepFocusInReferences` but for `LspDiagShow` rather than `LspShowReferences`. Note that the default behaviour is changed by this PR as  `keepFocusInDiags` defaults to false.

Add `keepFocusInDiags` option

---

autoload/lsp/lsp.vim

Right now with `ignoreMissingServer` set, when calling `LspAddServer()` with a list of servers where the very first entry is invalid, but the remaining ones are valid, no servers are added.
It seems highly unintuitive to me that the `ignoreMissingServer` option only silences the warning, but still aborts the whole call even if the remaining servers in the list are valid.
For example, I am calling:
```vim
au VimEnter * call LspAddServer([
\ #{ name: 'nix', filetype: ['nix'], path: 'nil' },
\ #{ name: 'bash', filetype: ['sh'], path: 'bash-language-server', args: ['start'] },
\ #{ name: 'cpp', filetype: ['c', 'cpp'], path: 'clangd', args: ['--background-index'] },
\ #{ name: 'haskell', filetype: ['haskell'], path: 'haskell-language-server', args: ['--lsp'] },
\ #{ name: 'qml', filetype: …
```

Skip invalid servers instead of aborting

---

autoload/lsp/outline.vim
autoload/lsp/symbol.vim
autoload/lsp/textedit.vim
test/clangd_tests.vim

I don't have exact steps to reproduce this, but sometimes the LSP sends back some invalid data, such that in `PeekLocations()`, `getbufline()` will return an empty set, causing the `[0]` to be out of bounds:
```
Error detected while processing function lsp#lsp#ShowReferences[6]..<SNR>62_ShowReferences[20]..lsp#symbol#ShowLocatio
ns[2]..<SNR>70_PeekLocations:
line   21:
E684: List index out of range: 0
```
Luckily this can easily be fixed by replacing `getbufline()[0]` with `getbufoneline()`, which will just return an empty string in those cases and avoid the error.

Fix rare out-of-bounds issue with getbufline()

---

autoload/lsp/completion.vim

The branch for LSP servers providing documentation on demand via "resolveProvider" already fixed this, but documentation can also be available without the completionLazyDoc setting. Since the style of the info popup shouldn't differ in these cases, let's unify the `completepopup` style for both branches. Otherwise the colors of the info popup might look weird if they are colored with `PmenuSel`:

Fix completepopup colors

---

autoload/lsp/completion.vim
autoload/lsp/options.vim
doc/lsp.txt

This enhancement enables **hrsh7th/vim-vsnip** plugin to complete user defined snippets. Without this enhancement vim-vsnip could only expand LSP provided snippets.
- Query vim-vsnip plugin for snippet completions and add the items to the completion list.
- Add a boolean flag to set vsnip completion option
- Update documentation
- Based on hrsh7th/cmp-vsnip
[required] hrsh7th/vim-vsnip
[required] hrsh7th/vim-vsnip-integ
[optional] rafamadriz/friendly-snippets
```
completionTextEdit: false,
snippetSupport: true,
vsnipSupport: true,
ultisnipsSupport: false,
```
Completion is not triggered for non-keyword characters like '#' (ex. # before #if in C) even though _vim-vsnip_ interface is capable of such completion, unless LSP server sets special characters as trigger characters. This is not a …

Add support for hrsh7th/vim-vsnip plugin

---

README.md
autoload/lsp/diag.vim
autoload/lsp/options.vim
autoload/lsp/util.vim
doc/lsp.txt

This adds an `aleSupport` option that is off by default. If enabled, the plugin will send all diagnostics to [Ale](https://github.com/dense-analysis/ale) which allows them to be displayed together with all other linter warnings and improves integration, e.g. all diagnostics will be available in the location list regardless of whether they come from Ale or if they come from lsp.
This is the equivalent to the `"diagnostic.displayByAle"` option in coc.nvim.
Here is a demo where all linter warnings and LSP warnings are displayed nicely together:
The first warning comes from clazy (a linter, that is not available as LSP and only in Ale) and the second and third warning come from lsp, which were then sent to Ale for display.

Implement Ale integration support

---

autoload/lsp/completion.vim
autoload/lsp/options.vim
doc/lsp.txt

Since buffer completion processes the current buffer everytime user types something, it will degrade the experience for large files.
This change adds a timeout to buffer completor function. Processing current buffer is cut short when timeout is exceeded. Setting timeout to 0 will revert back to existing behaviour.
Default is set to 100 ms, good for scanning 6000 lines on M1 macbook.
It is possible to get fancy by scanning locality of cursor first but such complication may not be worth the complexity.
Tested on >20k line files (I have to open these large C files filled with hw specs occasionally).
M  autoload/lsp/options.vim
M  doc/lsp.txt

Make buffer completion responsive for large files

---

autoload/lsp/diag.vim
test/clangd_tests.vim

In 6e4ba22, a regression was introduced, that caused this plugin to
ignore both the aleSupport and the autoHighlightDiags option when
reloading a buffer, meaning that the plugin would highlight diagnostics
even when the user explicitly told it not to.

Respect autoHighlightDiags when reloading a buffer

---

autoload/lsp/completion.vim
doc/lsp.txt

There are 2 changes in this PR.
1) Reduce regex comparison overhead in `LspOmniFunc()`.
2) Add a new function to check if LSP server has responded to request from omnifunc. With this change it is possible to write adapters to external async completion plugins. See document (`lsp.txt`) for more details.

Omnifunc optimization and readiness indicator

---

autoload/lsp/markdown.vim

Compute correct position of the line break and of the end of the text property when splitting the line.
Add the correct list of text properties for heading block.

Fix markdown parser

---

autoload/lsp/markdown.vim
test/markdown_tests.vim

Fix SplitLine function when text contains multibyte characters.
Strip leading and trailing whitespaces in heading.
Add tests for line breaks.

Markdown parser fix for contents with multibyte characters

---

autoload/lsp/completion.vim

When using Omni completion with other sources of completion items that do not have 'user_data' dictionary, documentation popup should not throw error.
I am using my own completion plugin with g:LspOmniFunc and I need LSP to grab lazy-doc from lsp server. But it should not throw error when user_data does not contain dictionary.

omnifunc documentation popup should not throw error

---

autoload/lsp/handlers.vim

Ignore `eslint/status` and `taplo/didChangeSchemaAssociation` unsupported notification messages

fix: ignore `eslint/status` and `taplo/didChangeSchemaAssociation`

---

autoload/lsp/completion.vim
autoload/lsp/textedit.vim

This patch implements support for the optional "command" field in the `CompletionItem` response to a "completionItem/resolve" request: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem
Some language servers (e.g. haskell-language-server) use this field to apply other edits to the document (e.g. auto-importing functions).
While the spec technically says that "additionalTextEdits" should be used for that usecase (also see #367), apparently not all servers do and I can see the reason, because haskell-language-server also wants to show an "window/showMessage" info message to the user about the auto-import.

Add support for CompletionItem commands

---

autoload/lsp/lspserver.vim

It's possible for diagnostics to arrive before the initialization message, causing:
```
Error detected while processing function <SNR>23_Output_cb[5]..lsp#handlers#ProcessMessages[32]..lsp#handlers#ProcesNotif[38]..<SNR>24_ProcessDiagNotif[2]..lsp#diag#DiagNotification:
line   15:
E716: Key not present in Dictionary: "needOffsetEncoding"
E716: Key not present in Dictionary: "needOffsetEncoding"
```
Ensuring the key is initialized in `NewLspServer` is one way to fix it.

fix: initialize needOffsetEncoding in NewLspServer

---

autoload/lsp/completion.vim

The logic was accidentally broken for the case where the LSP server already had the additionalTextEdits info ready.
Also see #389

Fix additionalTextEdits being ignored

---

doc/lsp.txt

The filetype specified in the example snippet is wrong

Fix filetype error in docs

---

autoload/lsp/textedit.vim
test/clangd_tests.vim

Currently the `ApplyTextEdits()` code loses the cursor position, because it applies the text edits by deleting the entire range with `deletebufline()` and then adding the new range with `appendbufline()`.
Obviously the cursor will move, if it happens to be inside this range, which is often the case (e.g. when renaming a variable).
This is also apparently the reason, why in the past there was a workaround that saved the cursor position before applying any edits, and then restored it afterwards.
That workaround was already (correctly) removed with: https://github.com/yegappan/lsp/pull/389#issuecomment-1705501598
Instead of reintroducing the workaround, this patch avoids losing the cursor position altogether by not deleting the entire range, but only deleting lines that actually need to be …

Avoid moving the cursor when applying textedits

---

autoload/lsp/completion.vim
autoload/lsp/lspserver.vim
test/clangd_tests.vim

Fixed 2 bugs:
- add triggerCharacters to lsp list for omniComplete option
- process triggerCharacters based keywords in omnifunc()
M  autoload/lsp/lspserver.vim

Make omnifunc() complete keywords based on LSP triggerCharacters

---

autoload/lsp/completion.vim

This is what pyslp sent:
{'label': '''H''', 'data': {'doc_uri': 'file:///filename.py'},'sortText': 'a''H''', 'kind': null, 'insertText': '''H'''}
'kind' property need to be checked for null before attempting completion.

Remove E1013 error when lsp sends kind=null

---

doc/lsp.txt

I could not get omnicomplete to work when setting the options after adding the servers

change order of vim-plug initialization commands

---

autoload/lsp/hover.vim

The original few lines of code are redundant.
Just return false and let vim handle the other keys. The redundant code disabled mouse scrolling, and the popup will be closed automatically after some seconds (I don't know why it is closed automatically)

fix: hover popup-filter, remove redundant code

---

autoload/lsp/inlayhints.vim

Add an extra space to LspInlayHintsParam to make it legible

---

autoload/lsp/signature.vim
autoload/lsp/symbol.vim
doc/lsp.txt

Add 1 character padding to the sides of signature popup window. Otherise, the leftmost character of popup looks like continuation of line from underneath text in some colorschemes. A subtle improvemnt.
M  autoload/lsp/signature.vim

Improve signature popup window

---

autoload/lsp/completion.vim

In LspOmniFunc() when cItems is empty (when findstart=1) it does not set the key 'completeItemsIsIncomplete' in the lspserver dictionary. When LspOmniFunc is called again with findstart=0, it fails.
```
line   46:
E716: Key not present in Dictionary: "completeItemsIsIncomplete"
```
This affects rust, nix, and other lsp servers:
https://github.com/girishji/vimcomplete/issues/14

BUG: LspOmniFunc() throws E716

---

README.md
autoload/lsp/diag.vim
autoload/lsp/options.vim
doc/lsp.txt

There's currently not a way to configure the wrapping mode of diagnostic virtual text. This prevents users from configuring diagnostics like the default in neovim, which is after the line containing the error and truncated when too long.
This PR adds a configuration option that lets the wrapping mode be forced to either 'wrap' or 'truncate', or kept as it was before this PR ('default', the default value, which uses 'wrap' for 'after' and 'truncate' for 'above' and 'below').

Add: diagnostic virtual text wrapping mode option

---

autoload/lsp/hover.vim

Previously, popup window minwidth was set to 80. This means, if a popup window have text less than 80 character, it will keep some extra spaces until popup reaches 80 characters. For example:
But keeping minwidth to default, removes those extra spaces and the popup window looks nicer.

Improve popup window

---

autoload/lsp/completion.vim

pylsp was not displaying documentation from lsp server. this fixes the problem.
user does not have to enable omnicomplete for each file type when main option omniComplete is already enabled.

bug: 'Lazy doc' completion broken for omnifunc

---

autoload/lsp/handlers.vim

Yegappan plugin only support insiders version. 
My version: `@tailwindcss/language-server@0.0.0-insiders.81bfb90`

fix: ignore unsupported notification messages from tailwindcss-language-server

---

autoload/lsp/markdown.vim
test/markdown_tests.vim

While using the Pyright lsp, I noticed some non-breaking space entities `&nbsp;` in the hover docs.
This update replaces the entities with spaces.
Requests - Before
Requests  - After
Textual - Before
Textual - After

Unescape non-breaking spaces

---

autoload/lsp/diag.vim

This fixes the following error by falling back to `info` severity:
```
Error detected while processing function <SNR>66_Output_cb[5]..lsp#handlers#ProcessMess
ages[32]..lsp#handlers#ProcessNotif[52]..<SNR>67_ProcessDiagNotif[2]..lsp#diag#DiagNoti
fication[72]..lsp#diag#ProcessNewDiags[5]..<SNR>69_SendAleDiags[14]..<lambda>46:
line    6:
E716: Key not present in Dictionary: "severity"
```

Fix crash with neocmakelsp + ale

---

autoload/lsp/lsp.vim

g:LspAddServer can be called multiple times for various reasons. This PR prevents that by checking if an LSP server with the same name has already been added for that filetype and returning early if one is found.
Reasons that LspAddServer might be called multiple times include being added in a filetype plugin or when the vimrc is sourced multiple times.
This possibly fixes #522 and some other performance issues. I accidentally found this when it bogged down vim and noticed that some lines are called hundreds of thousands of times in just a few keystrokes. 
```FUNCTION  lsp#buffer#BufLspServerGet()
Defined: ~/.vim/pack/downloads/opt/lsp/autoload/lsp/buffer.vim:66
Called 8067 times
Total time:  11.400077000
Self time:   5.663494000
count     total (s)      self (s)
8067 …
```

Fix adding server multiple times

---

doc/lsp.txt
plugin/lsp.vim

As convenience complementing, say `xnoremap  gw  :LspFormat<cr>`

add lsp format operator mapping

---

autoload/lsp/lsp.vim

If the original server list is used, it is cleared during the step of removing filetype buffers, so no servers are actually restarted, as the `lspservers` list is empty by the time the `for` loop is reached.
Fixes #378

Use a copy of the server list when restarting

---

autoload/lsp/lsp.vim

Solves issue: https://github.com/yegappan/lsp/issues/

fix: wrap `didSaveFile` method with `try-finally` block

---

autoload/lsp/lspserver.vim

Do not check for digits in request.id

---

plugin/lsp.vim

See https://github.com/yegappan/lsp/commit/c8135167184b277db9940b075b3d8a6142614b74#comments

export function

---

autoload/lsp/diag.vim

The LSP specification defines the diagnostic severity as being optional, defaulting to Error. Properly handle such cases.
This patch also complements commit
5b94bf7635de39979e81f9dace85b94d248a67e8, which fixed the issue but only for when using the ALE integration. At the same time, it fixes it by using severity Error as the default, rather than Information.

Support optional diagnostic severity

---

autoload/lsp/signature.vim

@yegappan 
Closes https://github.com/yegappan/lsp/issues/525

Set space to `<Space`>

---

autoload/lsp/buffer.vim
autoload/lsp/lsp.vim
autoload/lsp/lspserver.vim

This feature is for lsp server with custom locations request(e.g. [ccls](https://github.com/MaskRay/ccls)). It's similar to [CocLocations](https://github.com/neoclide/coc.nvim/blob/baac60ac1676cd5640648af9f07c15be24041a3e/doc/coc.txt#L783) in coc.nvim.
Example config for ccls
```vim
nmap <buffer> <localleader>f <scriptcmd>g:LspFindLocations('ccls', false, "textDocument/references", {"excludeRole": 32})<cr>
nmap <buffer> <localleader>M <scriptcmd>g:LspFindLocations('ccls', false, "textDocument/references", {"role": 64})<cr>
nmap <buffer> <localleader>r <scriptcmd>g:LspFindLocations('ccls', false, "textDocument/references", {"role": 8})<cr>
nmap <buffer> <localleader>w <scriptcmd>g:LspFindLocations('ccls', false, "textDocument/references", {"role": 16})<cr>
nmap <buffer> <localleader>b …
```

Support custom locations request

---

doc/configs.md

This is also a call for help as I wonder how to convert the settings options; do these have to added to the `initializationOptions`? Or do they depend on the LS?

doc: expand conversion instructions from nvim-lspconfig

---

doc/lsp.txt

Current sample code as pasted will result in:
```
Error detected while processing function <SNR>73_Output_cb[5]..lsp#handlers#ProcessMessages[32]..lsp#handlers#ProcessNotif[52]..<SNR>74_ProcessDiagNotif[2]..lsp#diag#DiagNotification[24]..<lambda>31[5]..<lambda>32:
line    1:
E715: Dictionary required
```
Swapping the order corrects this issue.

docs(processDiagHandler): wrong order of args

---

autoload/lsp/completion.vim
autoload/lsp/lsp.vim
autoload/lsp/signature.vim
doc/lsp.txt

This extends PR #620 with popup customization options for the completion popup and signature help popup.
The completion popup uses the same defaults as the other popups from #620. The signature help popups default to the current style (`Pmenu` highlight and no border) so will not be annoying to people who like the current, single line signature help look.

Configure Completion and SignatureHelp popups

---

autoload/lsp/completion.vim
autoload/lsp/options.vim
doc/lsp.txt

Optional list of LSP server names for which
'IsIncomplete' messages should be ignored and
filtering of received completion item lists
is enforced. This is helpful for LSP servers
that are misbehaving and always send this
kind of 'IsIncomplete' messages.

Adds the option ignoreCompleteItemsIsIncomplete.

---

autoload/lsp/diag.vim
doc/lsp.txt

This addition adds configurations options for the
border sizes and border characters of diagnostic
messages popups, which are shown with the command
:LspDiagnosticCurrent.

Add configuration for border of diagnostic popups.

---

autoload/lsp/symbol.vim

This change allows base syntax-highlighting to bleed through the `LspSymbolName` and `LspSymbolName` highlights when using `:LspDocumentSymbol`:
```vim
colorscheme retrobox
hlset([
{name: 'LspSymbolName', cterm: {bold: true}, guibg: '#303030'},
{name: 'LspSymbolRange', cterm: {bold: true}, guibg: '#3c3836'}
])
```
Before:
After:
I can't think of any downside to using `combine: true` but I may have missed something?

Combine LspSymbol prop types

---

README.md
autoload/lsp/lspserver.vim
doc/lsp.txt

It also improves warnmsg as @Shane-XB-Qian suggested in #587

Update docs for g:LspFindLocations

---

autoload/lsp/lspserver.vim

According to the [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#shutdown) the param value for the 'shutdown' request sent from the client
to the server should be 'none' not '{}'.
The current implementation of sending the value '{}' makes the LSP server [ty](https://github.com/astral-sh/ty) complain
about a JSON parsing failure:
```
Method: shutdown
error: invalid type map, expected unit
```
**This fix has been tested successfully with the following LSP servers:**
- clangd
- rust-analyser
- gopls
- ruff
- ty
- jdtls
**Log & trace details:**
__lsp-ty.log:__
```
06/12/25 18:18:13: Sent {'method': 'shutdown', 'params': {}}
06/12/25 18:18:13: Received {'method': 'textDocument/publishDiagnostics', 'jsonr
pc': '2.0', 'params': …
```

Change LSP  shutdown-command parameter to 'v:null' instead of '{}'

---

autoload/lsp/textedit.vim

Vim has issues when buffer lines are deleted, which have text properties assigned to them.
See:
- [internal errors after removing multiline text property](github.com/vim/vim/issues/12568)
- [Internal errors E340 E685 when buffer lines are deleted, which have text properties assigned](https://github.com/vim/vim/issues/18136)
This might even lead to segfaulting Vim.
Solution:
In order to prevent such an issue the text properties are explicitly cleared before the lines are deleted.
References:
[internal errors after removing multiline text property](github.com/vim/vim/issues/12568)
[Internal errors E340 E685 when buffer lines are deleted, which have text properties assigned](https://github.com/vim/vim/issues/18136)

Explicitly clear text properties before deleting lines to prevent Vim E340, E685

---

autoload/lsp/handlers.vim

The lua-language-server LSP implementation sends a "hello world" message whenever it is started. Specifically, it sends: `{"jsonrpc":"2.0","method":"$/hello","params":["world"]}`.
This change simply adds the message to the list of ignored notifications to silence the resulting error when attaching this server to a lua file.

Silence 'Unsupported notification message' for lua-language-server

---

autoload/lsp/symbol.vim

`m'` might be mapped in user config and do something unexpected.

Use `normal! m'`

---

autoload/lsp/capabilities.vim
autoload/lsp/codeaction.vim
autoload/lsp/lspserver.vim

This adds support for resolving the `edit` and `command` properties of `CodeAction` objects.
Tested as working with OmniSharp (see #674). Tested as not breaking rust-analyzer.

Add CodeAction resolve support (#674)

---

README.md
autoload/lsp/completion.vim
autoload/lsp/options.vim
doc/lsp.txt

This PR adds support for forcing broader completions with both omnicomplete and 24x7 completion. 
Note that the omnicomplete solution isn't great, because there's no direct way to specify more granular triggers. This is mainly a problem if `set complete+=o`, but shouldn't be noticeable elsewhere as long as the trigger is exclusively manual. Both the force options are opt-in, and have two different methods. 24x7 completion currently goes via the `LspComplete` function, where a `force` option that defaults to false was added. This probably isn't optimal. I'm not sure if another API for end-users is better, but this can be dealt with in review. It should be opt-in, however, as if it defaults to true, it'll suffer from the same problems as omnicomplete, but by default and for everyone. …

Allow bare omnicomplete
